# This workflow will deploy documentation to gh-pages and release a new version on npm

name: Deploy

on:
    release:
        types: [published]

jobs:
    deploy-documentation:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run docs:build
            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: .

    deploy-package:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
                  registry-url: 'https://registry.npmjs.org'
            - run: npm ci
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

    notify:
        name: Discord Notification
        runs-on: ubuntu-latest
        needs: # make sure the notification is sent AFTER the jobs you want included have completed
            - deploy-documentation
            - deploy-package
        if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
        steps:
            - name: Notify
              uses: nobrayner/discord-webhook@v1
              with:
                  github-token: ${{ secrets.github_token }}
                  discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
